bug fixes
logmanager-oss/logveil pull request #17
Opened 2024-11-26 10:48 UTC by tender-barbarian

Some bugs were discovered during testing:

1. Incorrect flags parsing
2. Proof writer buffer not flushing on code exit
3. Performance improvements
4. Graceful closing on interrupts

2025-01-22 08:59 UTC, elvecz requested changes

2025-01-22 08:59 UTC, elvecz commented on internal/reader/backup.go
> +	const maxCapacity = 4000000
I'd like to see this value as input somewhere, not hardcoded in source code

2025-01-22 08:59 UTC, elvecz commented on internal/writer/writer.go
> +	const maxCapacity = 2000000
I'd like to see this value as input somewhere, not hardcoded in source code

2025-01-22 08:59 UTC, elvecz commented on internal/loader/loader.go
> +				slog.Error("wrong custom mapping: %s", "error", line)
As we are (currently) using slog, but in future it could be another logging library, consider please to create Logger as a dependency and is it, instead of direct call of library.

2025-01-22 08:59 UTC, elvecz commented on internal/proof/proof.go
> +		const maxCapacity = 1000000
I'd like to see this value as input somewhere, not hardcoded in source code

2025-01-23 10:43 UTC, tender-barbarian commented on internal/reader/backup.go
> +	const maxCapacity = 4000000
done

2025-01-23 10:44 UTC, tender-barbarian commented on internal/proof/proof.go
> +		const maxCapacity = 1000000
done

2025-01-23 10:44 UTC, tender-barbarian commented on internal/writer/writer.go
> +	const maxCapacity = 2000000
done

2025-01-23 19:09 UTC, elvecz approved these changes
Nice! Thanks!

2025-01-23 19:10 UTC, merged